#pragma once

#include <cstdint>

/*
===============================================================================
Wirekrak Control-Plane Request IDs
===============================================================================

This header defines the **reserved request ID space** for protocol control-plane
messages (e.g. ping, keepalive, health probes).

Request ID Contract
-------------------

Wirekrak partitions the request ID space into two domains:

  - req_id == 0
      Invalid. Never used.

  - req_id in [1..9]
      Reserved for control-plane messages.
      Intentionally small because these are semantic protocol signals,
      not an extensible namespace.

      These IDs are:
        - Explicit
        - Non-sequenced
        - Non-replayable
        - Not subject to subscription semantics

  - req_id >= 10
      Protocol-plane request IDs.
      Used for subscriptions, unsubscriptions, and all stateful protocol flows.
      Generated by a monotonic sequence.

Rationale
---------

Separating control-plane and protocol-plane identifiers:

  - Prevents accidental inference or optimistic state
  - Preserves deterministic behavior across reconnects
  - Allows forward-compatible introduction of new control messages
  - Keeps protocol semantics explicit and auditable

This is a structural invariant of Wirekrak Core.
===============================================================================
*/

namespace wirekrak::core::protocol::control {

// -----------------------------------------------------------------------------
// Reserved control-plane request IDs
// -----------------------------------------------------------------------------

/// Explicit ping request (liveness / RTT measurement)
static constexpr std::uint64_t PING_ID = 1;

/// First valid protocol-plane request ID
static constexpr std::uint64_t PROTOCOL_BASE = 10;

} // namespace wirekrak::core::protocol::control
